### ISSUE TITLE
Add Javalin example

### ISSUE THREAD

**Issue by olle** [olle/serverside-todomvc#5]
Because it looks great! 👍 

Ping @tipsy

**Comment by olle** [comment]
I'm doing it. Look, it only took 5 years to get going. 😱

**Comment by tipsy** [comment]
Haha, good luck!

**Comment by olle** [comment]
Done, brute forced it. But Javalin _feels_ really malleable and complete. Merry X-mas!

**Comment by tipsy** [comment]
Merry Christmas! :christmas_tree:
